cookie:
  expiry_days: 30
  key: dDy2g
  name: 9Oj
credentials:
  usernames:
    arthur:
      email: arthur@gmail.com
      name: arthur
      password: $2b$12$b9bIqkxVaSfCEJvPf80YI.GctaQ6PUeT4QGBORHZ4HSZ0Zt6GJ8nG
    joachim:
      email: joachim@gmail.com
      name: joachim
      password: $2b$12$xfJGQQNZ2xrL2nQYZdlkweg4NKl0ky3oqdI4mi6KE5eBDt9C8/o4y
    marchepas:
      email: marchepas@gmail.com
      name: marchepas
      password: $2b$12$wpOzBGu.lAqcmBz2srIypOarvtoKeDkhuz/PVGI8dmLsEMmOr6sci
    nul:
      email: nul@gmail.com
      name: nul
      password: $2b$12$/ZsNuJGMPPlg4ea3kq5gOOaw1vZ7rh7VCkcUS30yX07EMeIbKhIF.
    pierre:
      email: pierregia13@gmail.com
      name: pierre
      password: $2b$12$qINvWSdNY/WjxcrybcWsq.cpBZSjGDD45MgZqPrzqVoIdmPFL4PQO
    pourquoi:
      email: pourquoi@gmail.com
      name: pourquoi
      password: $2b$12$gqgXSGEND9k8LHT3ubiMf.HhwRiGVEWX/kMGaBsCQEJKo3Hb7tRcO
    test:
      email: test@gmail.com
      name: test
      password: $2b$12$6es72Ns6HRqdvU51.md5juJEZpRLjmdjR3PgdAaGE.1tKsd1h9J/m
prehautorized:
  emails: antonys@simplon.co
  