cookie:
  expiry_days: 30
  key: rWwI8
  name: LAf
credentials:
  usernames:
    jojo:
      email: jojo@gmail.com
      name: lombardi
      password: $2b$12$.K7Rd6eMljM3oAz.0DkG4ODh3sw3QabZTg0gSwyzO21Ya1PCKu59S
    juju:
      email: juju@mail.com
      name: julo
      password: $2b$12$Wsf/LPHVRVRSnWE3H.NnmePcxfmQnHlJVckqaMfFFd1XErB8Y.rpy
    lola:
      email: lola@gmail.com
      name: lolo
      password: $2b$12$/ZJPMlH.gIjkjNF8Km563ugWcw6.ULeA6gMprAho0JBwbctb3tpBS
prehautorized:
  emails: antonys@simplon.co
